name: Build Intel platforms

on:
  push: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      toolchain: GCC5
    strategy:
      fail-fast: false
      matrix:
        platformname: 
          - BoardX58Ich10
          - GalagoPro3
          - KabylakeRvp3
          - UpXtreme
          - WhiskeylakeURvp
          - CometlakeURvp
          - TigerlakeURvp
          - WilsonCityRvp
        buildtarget: 
          - RELEASE
          - DEBUG
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            uuid-dev \
            iasl \
            git \
            gcc \
            nasm
          sudo apt-get clean

      - uses: actions/checkout@v2
        with:
          submodules: true 
      - run: git submodule foreach git submodule update --init --force --depth=1

      # Run the build commands
      - run: |
          cd edk2
          source ./edksetup.sh
          cd ..
          cd edk2-platforms/Platform/Intel
          python build_bios.py -t ${{ env.toolchain }} --${{ matrix.buildtarget }} -p ${{ matrix.platformname }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platformname }}_${{ matrix.buildtarget }}_${{ env.toolchain }}
          path: Build/**/${{ matrix.buildtarget }}_${{ env.toolchain }}/FV/*.fd
